name: Cypress Tests
on:
  push:
    branches: [ main, feature/*]
  pull_request:
    branches: [ main, release/develop ]
  workflow_dispatch:
    inputs:
      ambiente:
        description: 'Inserir o ambiente a ser executado os testes: dev / qa / hlg / prd'
        required: false
        default: 'qa'
      browser:
        description: 'Selecionar algum destes browsers: chrome / electron  a ser executado os testes'
        type: choice
        options:
          - chrome
          - electron
          - firefox
        required: true
jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1
    
    # steps:
    # - name: Checkout
    #   user: action/checkout@v3

    # - name: Cypress install
    #   user: cypress-io/github-action@v5
    #   with:
    #     runTests: false
    # - run: yarn cypress info

  # cypress-run-tests-cloud:
  #   name: Cypress run cloud
  #   runs-on: ubuntu-latest
  #   container:
  #     image: cypress/browsers:node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1
    
  #   needs: prepare-environment
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       containers: [1, 2] # Uses 2 parallel instances

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install dependencies
  #       uses: cypress-io/github-action@v6
  #       with:
  #         runTests: false

  #     - name: Cypress run tests
  #       uses: cypress-io/github-action@v6
  #       with:
  #         record: true
  #         # start: npm start
  #         # wait-on: 'https://blogdoagi.com.br/'
  #         record: true
  #         parallel: true
  #         browser: ${{ github.event.inputs.browser || 'chrome' }}
  #       env:
  #         # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
  #         # in GitHub repo → Settings → Secrets → Actions
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #         ENVIRONMENT: ${{ github.event.inputs.ambiente || 'qa' }}
  #         # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}